package combos;

public enum ComboType{
    None,
    Single,
    Pair,
    Consequtive2Pairs,
    Consequtive3Pairs,
    Consequtive4Pairs,
    Consequtive5Pairs,
    Consequtive6Pairs,
    Consequtive7Pairs,
    Tripple,
    FullHouse,
    Straight5,
    Straight6,
    Straight7,
    Straight8,
    Straight9,
    Straight10,
    Straight11,
    Straight12,
    Straight13,
    Straight14,
    Straight5Bomb,
    Straight6Bomb,
    Straight7Bomb,
    Straight8Bomb,
    Straight9Bomb,
    Straight10Bomb,
    Straight11Bomb,
    Straight12Bomb,
    Straight13Bomb,
    QuartetBomb
}
